#!/bin/sh -l

sh -c "echo Hello world my name is $INPUT_MY_NAME"

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
